name: halloween_battle
description: A turn based PvP game.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flame: 1.6.0
  flame_audio: 1.3.5
  supabase_flutter: 0.3.3
  supabase: 0.3.6
  provider: 6.0.5
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.5

dev_dependencies:
  flutter_launcher_icons: 0.11.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/HalloweenBattleLogo.png"
  flutter_lints: 1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
  fonts:
    - family: Fruktur
      fonts:
        - asset: assets/fonts/Fruktur/Fruktur-Regular.ttf
